title: 平台介绍 
description: 总体介绍平台，了解功能、开发方式
order: [custom.rst, 
        pkg.rst, 
        hello.rst, 
        lightweight.rst, 
        dingcan, 
        faq.rst, 
        python.rst, 
       ]
exclude: [img, pic, index.rst]
